### ISSUE TITLE
RTK_Everywhere_Firmware_RC-Apr_24_2024.bin - compiled with debug flags

### ISSUE THREAD

**Issue by doug-foster** [sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries#1]
### Subject of the issue
- Verify debug messages are off for repo binaries.
- No option to turn off *all* debug from serial config menu

### Your workbench
- EVK
- https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/blob/main/RTK_Everywhere_Firmware_RC-Apr_24_2024.bin

### Steps to reproduce
- Load RTK_Everywhere_Firmware_RC-Apr_24_2024.bin to EVKx

### Expected behavior
- "normal" boot messages on ESP

### Actual behavior
- boot messages follow:
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
E (873) esp_core_dump_flÅÊ¯°È No core dump partition found!
E (873) esp_core_dump_flash: No core dump partition found!
[     4][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[   456][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled

[   477][D][esp32-hal-adc.c:194] __analogReadMilliVolts(): eFuse Vref: Supported
[   478][I][esp32-hal-adc.c:235] __analogReadMilliVolts(): ADC1: Characterized using eFuse Vref: 1114

[   482][D][Begin.ino:64] identifyBoard(): Board ADC ID (mV): 2980
LittleFS Started
[   499][E][vfs_api.cpp:105] open(): /littlefs/configureViaEthernet.txt does not exist, no permits for creation
[   539][D][NVM.ino:1391] loadProfileNumber(): Using profile #0
PSRAM Size (bytes): 4192107
[  1007][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=21 scl=22 freq=100000
I2C Devices:
  0x42 - u-blox ZED-F9P GNSS Receiver
  0x43 - u-blox NEO-D9S Correction Data Receiver
[  1134][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=12 scl=15 freq=100000
I2C Devices:
  0x3D - SSD1306 OLED Driver
Display started
SparkFun RTK EVK d1.0
ZED-F9P firmware: HPG 1.32
GNSS ZED online
[  1872][D][Begin.ino:491] beginSD(): SD card detected
microSD: Online
[  2510][D][NVM.ino:150] recordSystemSettingsToFileSD(): Removing from SD: /SFE_EVK_Settings_0.txt
[  2573][D][NVM.ino:169] recordSystemSettingsToFileSD(): Settings recorded to SD: /SFE_EVK_Settings_0.txt
[  2593][D][NVM.ino:199] recordSystemSettingsToFileLFS(): Removing LittleFS: /SFE_EVK_Settings_0.txt
[  2779][D][NVM.ino:211] recordSystemSettingsToFileLFS(): Settings recorded to LittleFS: /SFE_EVK_Settings_0.txt
[  2941][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_1.txt does not exist, no permits for creation
[  2947][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_2.txt does not exist, no permits for creation
[  2955][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_3.txt does not exist, no permits for creation
[  2965][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_4.txt does not exist, no permits for creation
[  2974][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_5.txt does not exist, no permits for creation
[  2984][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_6.txt does not exist, no permits for creation
[  2994][E][vfs_api.cpp:105] open(): /littlefs/SFE_EVK_Settings_7.txt does not exist, no permits for creation
Profile 'Profile1' loaded
ZED-F9x configuration update
NEO-D9S firmware: PMP 1.04
System time set to: Thursday, April 25 2024 13:09:00
[  7310][D][NVM.ino:150] recordSystemSettingsToFileSD(): Removing from SD: /SFE_EVK_Settings_0.txt
[  7378][D][NVM.ino:169] recordSystemSettingsToFileSD(): Settings recorded to SD: /SFE_EVK_Settings_0.txt
[  8408][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_REG_EVT
[  8410][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_CREATE_EVT
[  8419][D][BLEService.cpp:225] addCharacteristic(): Adding characteristic: uuid=6e400002-b5a3-f393-e0a9-e50e24dcca9e to service: UUID: 6e400001-b5a3-f393-e0a9-e50e24dcca9e, handle: 0x0028
[  8435][D][BLEService.cpp:225] addCharacteristic(): Adding characteristic: uuid=6e400003-b5a3-f393-e0a9-e50e24dcca9e to service: UUID: 6e400001-b5a3-f393-e0a9-e50e24dcca9e, handle: 0x0028
[  8452][D][BLECharacteristic.cpp:90] executeCreate(): Registering characteristic (esp_ble_gatts_add_char): uuid: 6e400002-b5a3-f393-e0a9-e50e24dcca9e, service: UUID: 6e400001-b5a3-f393-e0a9-e50e24dcca9e, handle: 0x0028
[  8471][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_ADD_CHAR_EVT
[  8482][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_ADD_CHAR_DESCR_EVT
[  8493][D][BLECharacteristic.cpp:90] executeCreate(): Registering characteristic (esp_ble_gatts_add_char): uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e, service: UUID: 6e400001-b5a3-f393-e0a9-e50e24dcca9e, handle: 0x0028
[  8512][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_ADD_CHAR_EVT
[  8523][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_ADD_CHAR_DESCR_EVT
[  8535][D][BLEDevice.cpp:102] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_START_EVT
[  8545][I][BLEDevice.cpp:577] getAdvertising(): create advertising
[  8551][D][BLEDevice.cpp:579] getAdvertising(): get advertising
[  8557][D][BLEAdvertising.cpp:199] start(): - advertising service: 6e400001-b5a3-f393-e0a9-e50e24dcca9e
Bluetooth Low-Energy broadcasting as: EVK Rover-8F06
[  8577][D][NVM.ino:150] recordSystemSettingsToFileSD(): Removing from SD: /SFE_EVK_Settings_0.txt
[  8569][D][BLEDevice.cpp:579] getAdvertising(): get advertising
[  8585][D][BLEAdvertising.cpp:506] handleGAPEvent(): handleGAPEvent [event no: 0]
[  8592][D][BLEDevice.cpp:579] getAdvertising(): get advertising
[  8598][D][BLEAdvertising.cpp:506] handleGAPEvent(): handleGAPEvent [event no: 1]
[  8605][D][BLEDevice.cpp:579] getAdvertising(): get advertising
[  8611][D][BLEAdvertising.cpp:506] handleGAPEvent(): handleGAPEvent [event no: 6]
[  8647][D][NVM.ino:169] recordSystemSettingsToFileSD(): Settings recorded to SD: /SFE_EVK_Settings_0.txt
[  8670][D][NVM.ino:199] recordSystemSettingsToFileLFS(): Removing LittleFS: /SFE_EVK_Settings_0.txt
[  8980][D][NVM.ino:211] recordSystemSettingsToFileLFS(): Settings recorded to LittleFS: /SFE_EVK_Settings_0.txt
STATE_ROVER_NOT_STARTED --> STATE_ROVER_NO_FIX, 2024-04-25 13:09:02.177
[  9508][D][Begin.ino:1324] beginSDSizeCheckTask(): sdSizeCheck Task started
Rover Accuracy (m): 0.210, SIV: 28 GNSS State: 3D Fix
STATE_ROVER_NO_FIX --> STATE_ROVER_FIX, 2024-04-25 13:09:02.210
Rover Accuracy (m): 0.229, SIV: 28 GNSS State: 3D Fix
Rover Accuracy (m): 0.225, SIV: 28 GNSS State: 3D Fix

**Comment by nseidle** [comment]
Debug messages are enabled on RC binaries by design, and are [noted](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0RC) on releases.
